### ISSUE TITLE
Just hanging

### ISSUE THREAD

**Issue by johannspies** [aviks/SMTPClient.jl#17]
I cannot get SMTPClient.jl to work:

```
julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.3-pre.0 (2017-12-18 07:11 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 93168a6826* (86 days old release-0.6)
|__/                   |  x86_64-linux-gnu

julia> using SMTPClient

julia> opt = SendOptions(blocking = false, isSSL = false,
                         username = "")
SMTPClient.SendOptions(false, false, "", "")

julia> body = IOBuffer("""Date: Fri, 18 Oct 2013 21:44:29 +0100
       From: Johann Spies <jspies@sun.ac.za>
       To: Johann Spies <johann.spies@gmail.com>
       Subject: Julia Test

       Test Message""")
IOBuffer(data=UInt8[...], readable=true, writable=false, seekable=true, append=false, size=151, maxsize=Inf, ptr=1, mark=-1)

julia> resp = send("smtp://localhost:25", ["<Johann.spies@gmail.com>"], "<jspies@sun.ac.za>", body, opt)
```

This process never finishes.

**Comment by iblislin** [comment]
:thinking: I cannot reproduce that, I guess your mail server just drop the connection?
Could you try
```
$ telnet localhost 25
```
?

**Comment by johannspies** [comment]
On Thu, Mar 15, 2018 at 04:26:28AM +0000, Iblis Lin wrote:
> :thinking: I cannot reproduce that, I guess your mail server just drop the connection?
> Could you try
> ```
> $ telnet localhost 25
> ```
> ?
> 

telnet localhost 25
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 sitasie.sun.ac.za ESMTP Exim 4.90_1 Thu, 15 Mar 2018 08:43:30 +0200
ehlo sitasie
250-sitasie.sun.ac.za Hello localhost [127.0.0.1]
250-SIZE 52428800
250-8BITMIME
250-PIPELINING
250-CHUNKING
250-PRDR
250 HELP

Regards
Johann
-- 
Johann Spies                            Telefoon: 021-808 4699
Databestuurder /  Data manager		Faks: 021-883 3691

Sentrum vir Navorsing oor Evaluasie, Wetenskap en Tegnologie
Centre for Research on Evaluation, Science and Technology 
Universiteit Stellenbosch.

The integrity and confidentiality of this e-mail is governed by these terms / Die integriteit en vertroulikheid van hierdie e-pos word deur die volgende bepalings gereël. http://www.sun.ac.za/emaildisclaimer

**Comment by iblislin** [comment]
I got a segfault now. I guess there are some GC pitfalls. :man_facepalming:

**Comment by johannspies** [comment]
On Thu, Mar 15, 2018 at 07:41:19AM +0000, Iblis Lin wrote:
> I got a segfault now. I guess there are some GC pitfalls.

I previously also got a segfault.

Regards
Johann

-- 
Johann Spies                            Telefoon: 021-808 4699
Databestuurder /  Data manager		Faks: 021-883 3691

Sentrum vir Navorsing oor Evaluasie, Wetenskap en Tegnologie
Centre for Research on Evaluation, Science and Technology 
Universiteit Stellenbosch.

The integrity and confidentiality of this e-mail is governed by these terms / Die integriteit en vertroulikheid van hierdie e-pos word deur die volgende bepalings gereël. http://www.sun.ac.za/emaildisclaimer

**Comment by iblislin** [comment]
@johannspies Hi, I think the segfault is solved on master branch, it's for Julia 0.7/1.0.
Could you try it out?

**Comment by johannspies** [comment]
Thanks.  This timed I had success (on 1.0.2)  Much appreciated.

**Comment by iblislin** [comment]
We just tagged a new release -- SMTPClient v0.3.0.
Now you can simply add it via `Pkg.add`.
