### ISSUE TITLE
MethodError: no method matching send(::String, ::String, ::String, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::SendOptions)

### ISSUE THREAD

**Issue by juhyun-kim-ucla** [aviks/SMTPClient.jl#33]
When I use the `send(url, rcpt, from, body, opt)` command in Julia 0.7.0, it throws an error saying `Base.send` is deprecated. 
```
ERROR: LoadError: WARNING: Base.send is deprecated: it has been moved to the standard library package `Sockets`.
Add `using Sockets` to your imports.
 in module Base
MethodError: no method matching send(::String, ::String, ::String, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::SendOptions)
```
I tried to incorporate `Sockets` package, but was not sure how to get it to work. Let me know if I am missing something important. 
Thanks!

**Comment by iblislin** [comment]
https://github.com/aviks/SMTPClient.jl/blob/master/src/SMTPClient.jl#L7

I think we imported it already.

What is your version of SMTPClient?
