### ISSUE TITLE
Getting -> curl_easy_perform() failed: SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by logankilpatrick** [aviks/SMTPClient.jl#35]
Hey @aviks, 

I am getting: `curl_easy_perform() failed: SSL peer certificate or SSH remote key was not OK` when I run the example from the readme. 

Any thoughts to fix this?

**Comment by iblislin** [comment]
I guess that error is caused by untrusted certificate.
Ref: https://stackoverflow.com/a/20825555

**Comment by jeremiedb** [comment]
@logankilpatrick Have you managed to fix this? 
Are you on Windows? I'm on Windows and also have issues fixing the SSL peer certificate error message (though same script went fine with Ubuntu). Maybe is it tied to https://github.com/JuliaWeb/LibCURL.jl/issues/59? 
If you have a fix, let me know!

**Comment by logankilpatrick** [comment]
Hey, I haven’t got around to trying it again. I’ll ping you next week when I have more free time.

**Comment by jeremiedb** [comment]
For a quick unsecure fix, I managed to make it work adding `curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0)` following the curl initialization at: 
https://github.com/aviks/SMTPClient.jl/blob/57d5e3c771db219081cb3fdaa4b192e38f16eb53/src/types.jl#L70

**Comment by arnavs** [comment]
Can confirm that the fix above also works for me on 1.4.1
