### ISSUE TITLE
Higher level API

### ISSUE THREAD

**Issue by oxinabox** [aviks/SMTPClient.jl#40]
It would be nice if there was some convience overloads.
Such as being able to pass a the body as a string,
and being able to pass the message as a send-date `DateTime`,
 and subject string, a main content etc

**Comment by aviks** [comment]
Would be good to get a high level API. It's on my queue, but not sure when I will get to it. Would be nice to get a contribution for this. 

Also, do people have examples of good email-sending APIs? Which libraries should inspire us with their API design?

**Comment by jeremiedb** [comment]
Regarding a high level API, the one I'm aware of is R' Blastula: https://github.com/rstudio/blastula
It notably wraps a couple of helper for building more complex messages, including images, css, and handling credentials.

**Comment by oxinabox** [comment]
closed by #48
