### ISSUE TITLE
Doc example: Encoding an image file and sending as an attachment with SMTPClient.jl

### ISSUE THREAD

**Issue by allomorphy** [aviks/SMTPClient.jl#41]
Please will you include in your docs for this fine package and example of how to attach and send a graphic file.

Many thanks and best wishes
Eric

**Comment by qiyang-ustc** [comment]
This is also quite helpful for me.

**Comment by rmsrosa** [comment]
I found an easy way to add attachments! 

Needed it to send a bunch of jupyter notebooks back to my students, with nbgrader feedback.

Anyway. I will try to organize better what I did and make it more general. Hopefully I will have a PR by next week.
