### ISSUE TITLE
Installation using Pkg.add missing src-files

### ISSUE THREAD

**Issue by sbomsdorf** [aviks/SMTPClient.jl#50]
Hi, 

when trying to install the package using `Pkg.add("SMTPClient")`, `user.jl` and `mime_types.jl` are missing in the local installation. Last update of [https://juliapackages.com/p/smtpclient](https://juliapackages.com/p/smtpclient) has been 6 months ago, so it's probably just outdated?

Best,
Stefan

Edit: Use `]` and `dev https://github.com/aviks/SMTPClient.jl` in the REPL to avoid this issue.

**Comment by aviks** [comment]
Yeah, those files were added recently for new functionality, but a new, tagged version of this package had not been released in some time. A new tag has just been released. https://github.com/JuliaRegistries/General/pull/48548
